version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  main:
    docker:
      - image: 'cimg/python:3.9.2-browsers'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check browser installation
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Temp
          command: |
            pwd
            ls .
            ls ..
            ls ...
      - run:
          name: Install requirements
          command: |
            python -m pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python -m pytest

workflows:
 test:
   jobs:
      - main