version: 2.1

orbs:
  python: circleci/python@1.3.2
  browser-tools: circleci/browser-tools@1.1.3

jobs:
  install_browsers:
    docker:
      - image: 'cimg/node:13.12-browser'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install

workflows:
 test:
   jobs:
      - install_browsers
      - python/test:
          test-tool: pytest