version: 2.1

orbs:
 percy: percy/agent@0.1.3

jobs:
 run_tests:
   parallelism: 3
   steps:
     - attach_workspace:
         at: .
     - run: pytest

workflows:
 test:
   jobs:
     - run_tests
     - percy/finalize_all:
         requires:
           - run_tests
